### ISSUE TITLE
Add context about performance in actual deployments.

### ISSUE THREAD

**Issue by lovelydinosaur** [akaariai/drf-fast-serializer#2]
I'd assume that the SQLite benchmarks are going to be pretty skewed compared to database lookups on a real deployment. Because this package has the potential to have users make (possibly premature) optimizations, it'd be good to give them enough context to make a properly informed judgement.

Super useful package, but let's try to make sure that it doesn't misrepresent the impact it's able to have in actual deployments.
- Database lookups will typically be the limiting factor, not rendering the HTTP response body.
- Redis or Memcache caching of database lookups typically the big win.
- Ensuring proper indexes on database fields (anything user is ordering by, or looking up against).
- Ensuring usage of select_related and prefetch_related where appropriate.
- Usage of `.values()` as an option.

May be that it's then worth explaining that it's most likely to have an impact where:
- A large number of records are being serialised on each response.
- Data store access is not a limiting factor.

We might also want to add context by noting that _explicitly_ overriding `to_representation` on you serializer class is an alternative route that users might also want to consider.

**Comment by akaariai** [comment]
As long as you are serializing less than maybe 100-200 objects there is no point in this optimization.

The original case where I got the speed problem was querying a complex PostgreSQL view (approximately 10 joins) for around 10000 rows, and then serializing those rows to JSON. The view query took 500ms, DRF 2.4 serialization took 4s. With DRF 3 the serialization overhead is maybe somewhere around 1s (for total response time of 1.5s), and with the optimizations the response takes a bit less than 1s. It seems completely possible that there are real world use cases where DRF 3 + fast serialization will allow for 5x+ performance difference.

Still, these cases are likely a minority, and premature optimization is the root of all evil. So, mentioning that measuring if you have serialization bottleneck, and then considering if the trade-offs are worth the performance gain should be added.
